apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/redis-cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vesco
spec:
  capacity:
    storage: 512Mi
  storageClassName: hard-disk
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/vesco
